### ISSUE TITLE
Lộ private key và sensitive data

### ISSUE THREAD

**Issue by minhnq1618** [sloweyyy/ProjectX-LandingPage#9]
https://projectx-landing-page.vercel.app/secret.json

![image](https://github.com/sloweyyy/ProjectX-LandingPage/assets/81002476/02c2ae64-ed2b-4ef2-ae13-1e961ca7cc6e)

Cẩn thận hơn nhé các anh em đông lào của tôi

**Comment by sloweyyy** [comment]
Cảm ơn người anh em huhu
